apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  selector:
    matchLabels:
      app: express-app
  replicas: 2
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: react-app
          image: gcr.io/kubernetes-project-350417/github.com/ahmedameer1/express-docker
          ports:
            - containerPort: 3000
